### ISSUE TITLE
Add capability to print range of rows

### ISSUE THREAD

**Issue by phsym** [phsym/prettytable-rs#10]
### Tasks
- [x] Implement `TableSlice` type
- [x] Create `Slice` trait and implement it for `Table` and `TableSlice`
    - [x] With `Range`, `RangeTo` and `RangeFrom` to get a slice with only subrange of rows
    - [x] With `RangeFull` to get the slice with all the rows
- [x] Make `&Table` transmutable into `&TableSlice` so a table can be treated as a slice
- [X] Implement `AsRef<TableSlice<'a>>`, ~~and/or or `Borrow<TableSlice>`, and/or `Deref<TableSlice>`~~ for `Table`
- [x] Update Doc
- [x] Add an example
- [x] Update README

### Description
Create a struct `TableSlice<'a>` that wraps a ref to `Table`, which offers capability to print only a specific range of rows.
~~Perhaps slice syntax may be used to obtain this wrapper.~~
~~**eg :**~~
```rust
let mut table = Table::new();
/* (...) */
let slice: TableSlice<'a> = table[1..3];
```
**Edit :** Using slice syntax is not possible yet, since Index returns only references
Next idea is to create a `Slice<T>` trait with method `slice(&self, T) -> TableSlice<'a>` and implement it for `Table` and `TableSlice` with T as `Range`, `RangeFull`, `RangeFrom`, `RangeTo`

It will let us use the following syntax :
```rust
let mut table = Table::new();
/* (...) */
let slice: &'a TableSlice<'a> = table.as_ref();
let slice: TableSlice<'a> = table.slice(1..3);
let slice: TableSlice<'a> = table.slice(1..);
let slice: TableSlice<'a> = table.slice(..3);
let slice: TableSlice<'a> = table.slice(..);
```
